### ISSUE TITLE
Release profiles cannot be applied to sonarr running in docker

### ISSUE THREAD

**Issue by ajyey** [buildarr/buildarr#171]
I have an instance of sonarr running using docker compose and I am attempting to configure it with release profiles using buildarr. Here's my current setup

buildarr.yml
```yml
buildarr:
  watch_config: true
  update_days:
    - "monday"
    - "tuesday"
    - "wednesday"
    - "thursday"
    - "friday"
    - "saturday"
    - "sunday"
  update_times:
    - "03:00"

sonarr:
  host: "sonarr"
  port: 8989
  protocol: "http"
  api_key: my-api-key
  settings:
    profiles:
      release_profiles:
        definitions:
          Release Sources (Streaming Service):
            trash_id: 1B018E0C53EC825085DD911102E2CA36
          P2P Groups + Repack/Proper:
            trash_id: 71899E6C303A07AF0E4746EFF9873532
          Low Quality Groups:
            trash_id: EBC725268D687D588A20CBC5F97E538B
          Optionals:
            trash_id: 76e060895c5b8a765c310933da0a5357
            filter:
              include:
                - ea83f4740cec4df8112f3d6dd7c82751 # Prefer Season Packs
                - 6f2aefa61342a63387f2a90489e90790 # Dislike renamed/retagged releases
                - 19cd5ecc0a24bf493a75e80a51974cdd # Dislike retagged/obfuscated groups
                - 6a7b462c6caee4a991a9d8aa38ce2405 # Dislike release ending: en
                - 236a3626a07cacf5692c73cc947bc280 # Dislike release containing: 1-
                - cec8880b847dd5d31d29167ee0112b57 # Ignore 720p/1080p HEVC re-encodes (Golden Rule)
                - f3f0f3691c6a1988d4a02963e69d11f2 # Ignore The Group -SCENE
                - 5bc23c3a055a1a5d8bbe4fb49d80e0cb # Ignore so-called scene releases
                - 538bad00ee6f8aced8e0db5218b8484c # Ignore Bad Dual Audio Groups
                - 4861d8238f9234606df6721df6e27deb # Ignore AV1
```

docker-compose.yml
```yml
sonarr:
    image: lscr.io/linuxserver/sonarr
    container_name: sonarr
    ports:
      - "8989:8989"
    environment:
      - PUID=${USER_ID}
      - PGID=${GROUP_ID}
      - TZ=${TIMEZONE}
    volumes:
      - ./sonarr:/config
      - ${DATA_ROOT}:/data
    restart: always
    healthcheck:
      test: [ "CMD", "curl", "--fail", "http://127.0.0.1:8989/sonarr/ping" ]
      interval: 5s
      retries: 10
    labels:
      - homepage.group=Media
      - homepage.name=Sonarr
      - homepage.icon=sonarr.png
      - homepage.href=http://localhost:8989
      - homepage.description=Series management
      - homepage.weight=0
      - homepage.widget.type=sonarr
      - homepage.widget.url=http://sonarr:8989
      - homepage.widget.key=${SONARR_API_KEY}

buildarr:
    image: callum027/buildarr:latest
    container_name: buildarr
    restart: always
    volumes:
      - ./buildarr:/config:ro
    environment:
      TZ: ${TIMEZONE}
      PUID: "1000"
      PGID: "1000"
    depends_on:
      - sonarr
      - radarr
      - prowlarr
```

docker logs
```
2023-12-01T03:20:45.066698938Z 2023-11-30 22:20:45,064 buildarr:1 buildarr.cli.daemon [INFO] Buildarr version 0.7.1 (log level: INFO)
2023-12-01T03:20:45.066736383Z 2023-11-30 22:20:45,064 buildarr:1 buildarr.cli.daemon [INFO] Loading configuration file '/config/buildarr.yml'
2023-12-01T03:20:45.102985862Z 2023-11-30 22:20:45,102 buildarr:1 buildarr.cli.daemon [INFO] Finished loading configuration file
2023-12-01T03:20:45.104046906Z 2023-11-30 22:20:45,103 buildarr:1 buildarr.cli.daemon [INFO] Daemon configuration:
2023-12-01T03:20:45.104056770Z 2023-11-30 22:20:45,103 buildarr:1 buildarr.cli.daemon [INFO]  - Watch configuration files: Yes
2023-12-01T03:20:45.104059937Z 2023-11-30 22:20:45,103 buildarr:1 buildarr.cli.daemon [INFO]  - Configuration files to watch:
2023-12-01T03:20:45.104062615Z 2023-11-30 22:20:45,103 buildarr:1 buildarr.cli.daemon [INFO]    - /config/buildarr.yml
2023-12-01T03:20:45.104065073Z 2023-11-30 22:20:45,103 buildarr:1 buildarr.cli.daemon [INFO]  - Update at:
2023-12-01T03:20:45.104067463Z 2023-11-30 22:20:45,103 buildarr:1 buildarr.cli.daemon [INFO]    - Monday 03:00
2023-12-01T03:20:45.104069849Z 2023-11-30 22:20:45,103 buildarr:1 buildarr.cli.daemon [INFO]    - Tuesday 03:00
2023-12-01T03:20:45.104072249Z 2023-11-30 22:20:45,103 buildarr:1 buildarr.cli.daemon [INFO]    - Wednesday 03:00
2023-12-01T03:20:45.104074646Z 2023-11-30 22:20:45,103 buildarr:1 buildarr.cli.daemon [INFO]    - Thursday 03:00
2023-12-01T03:20:45.104077035Z 2023-11-30 22:20:45,103 buildarr:1 buildarr.cli.daemon [INFO]    - Friday 03:00
2023-12-01T03:20:45.104079429Z 2023-11-30 22:20:45,103 buildarr:1 buildarr.cli.daemon [INFO]    - Saturday 03:00
2023-12-01T03:20:45.104081854Z 2023-11-30 22:20:45,103 buildarr:1 buildarr.cli.daemon [INFO]    - Sunday 03:00
2023-12-01T03:20:45.104084240Z 2023-11-30 22:20:45,103 buildarr:1 buildarr.cli.daemon [INFO] Scheduling update jobs
2023-12-01T03:20:45.104086653Z 2023-11-30 22:20:45,103 buildarr:1 buildarr.cli.daemon [INFO] Finished scheduling update jobs
2023-12-01T03:20:45.104089072Z 2023-11-30 22:20:45,103 buildarr:1 buildarr.cli.daemon [INFO] Enabling config file monitoring
2023-12-01T03:20:45.106635963Z 2023-11-30 22:20:45,104 buildarr:1 buildarr.cli.daemon [INFO] Finished enabling config file monitoring
2023-12-01T03:20:45.106654805Z 2023-11-30 22:20:45,104 buildarr:1 buildarr.cli.daemon [INFO] Applying initial configuration
2023-12-01T03:20:45.106658074Z 2023-11-30 22:20:45,105 buildarr:1 buildarr.cli.run [INFO] Loaded plugins: jellyseerr (0.3.0), prowlarr (0.5.0), radarr (0.2.2), sonarr (0.6.1)
2023-12-01T03:20:45.106660967Z 2023-11-30 22:20:45,105 buildarr:1 buildarr.cli.run [INFO] Loading instance configurations
2023-12-01T03:20:45.113091754Z 2023-11-30 22:20:45,111 buildarr:1 buildarr.cli.run [INFO] Finished loading instance configurations
2023-12-01T03:20:45.113114298Z 2023-11-30 22:20:45,111 buildarr:1 buildarr.cli.run [INFO] Running with plugins: sonarr
2023-12-01T03:20:45.113117785Z 2023-11-30 22:20:45,111 buildarr:1 buildarr.cli.run [INFO] Resolving instance dependencies
2023-12-01T03:20:45.113127445Z 2023-11-30 22:20:45,111 buildarr:1 buildarr.cli.run [INFO] Finished resolving instance dependencies
2023-12-01T03:20:45.113149969Z 2023-11-30 22:20:45,111 buildarr:1 buildarr.cli.run [INFO] Fetching TRaSH metadata
2023-12-01T03:20:47.545117051Z 2023-11-30 22:20:47,544 buildarr:1 buildarr.cli.run [INFO] Finished fetching TRaSH metadata
2023-12-01T03:20:47.545136712Z 2023-11-30 22:20:47,545 buildarr:1 buildarr.cli.run [INFO] Rendering instance configuration dynamic attributes
2023-12-01T03:20:47.549262766Z 2023-11-30 22:20:47,549 buildarr:1 buildarr.cli.run [INFO] Finished rendering instance configuration dynamic attributes
2023-12-01T03:20:47.549485991Z 2023-11-30 22:20:47,549 buildarr:1 buildarr.cli.run [INFO] <sonarr> (default) Fetching instance secrets
2023-12-01T03:20:47.549694934Z 2023-11-30 22:20:47,549 buildarr:1 buildarr.cli.run [INFO] <sonarr> (default) Finished fetching instance secrets
2023-12-01T03:20:47.549909767Z 2023-11-30 22:20:47,549 buildarr:1 buildarr.cli.run [INFO] <sonarr> (default) Running connection test
2023-12-01T03:20:48.395369912Z 2023-11-30 22:20:48,395 buildarr:1 buildarr.cli.run [INFO] <sonarr> (default) Connection test successful
2023-12-01T03:20:48.395390592Z 2023-11-30 22:20:48,395 buildarr:1 buildarr.cli.run [INFO] Performing post-initialisation configuration render
2023-12-01T03:20:48.395394002Z 2023-11-30 22:20:48,395 buildarr:1 buildarr.cli.run [INFO] Finished performing post-initialisation configuration render
2023-12-01T03:20:48.395396615Z 2023-11-30 22:20:48,395 buildarr:1 buildarr.cli.run [INFO] Updating configuration on remote instances
2023-12-01T03:20:48.395399165Z 2023-11-30 22:20:48,395 buildarr:1 buildarr.cli.run [INFO] <sonarr> (default) Fetching remote configuration to check if updates are required
2023-12-01T03:20:49.753508468Z 2023-11-30 22:20:49,747 buildarr:1 buildarr.cli.run [INFO] <sonarr> (default) Finished fetching remote configuration
2023-12-01T03:20:49.762057741Z 2023-11-30 22:20:49,761 buildarr:1 buildarr.cli.run [INFO] <sonarr> (default) Updating remote configuration
2023-12-01T03:20:50.323421640Z 2023-11-30 22:20:50,323 buildarr:1 buildarr.config.base [INFO] <sonarr> (default) sonarr.settings.profiles.release_profiles.definitions['Release Sources (Streaming Service)'].enable: True -> (created)
2023-12-01T03:20:50.323676396Z 2023-11-30 22:20:50,323 buildarr:1 buildarr.config.base [INFO] <sonarr> (default) sonarr.settings.profiles.release_profiles.definitions['Release Sources (Streaming Service)'].must_contain: set() -> (created)
2023-12-01T03:20:50.323853285Z 2023-11-30 22:20:50,323 buildarr:1 buildarr.config.base [INFO] <sonarr> (default) sonarr.settings.profiles.release_profiles.definitions['Release Sources (Streaming Service)'].must_not_contain: set() -> (created)
2023-12-01T03:20:50.324138021Z 2023-11-30 22:20:50,324 buildarr:1 buildarr.config.base [INFO] <sonarr> (default) sonarr.settings.profiles.release_profiles.definitions['Release Sources (Streaming Service)'].preferred: [PreferredWord(term='/\\b(atvp|aptv|Apple TV\\+)\\b(?=[ ._-]web[ ._-]?(dl|rip)\\b)/i', score=100), PreferredWord(term='/\\b(dsnp|dsny|disney|Disney\\+)\\b(?=[ ._-]web[ ._-]?(dl|rip)\\b)/i', score=100), PreferredWord(term='/\\b((?<!hbo[ ._-])max)\\b(?=[ ._-]web[ ._-]?(dl|rip)\\b)/i', score=90), PreferredWord(term='/\\b(hmax|hbom|hbo[ ._-]max)\\b(?=[ ._-]web[ ._-]?(dl|rip)\\b)/i', score=80), PreferredWord(term='/\\b(qibi|quibi)\\b(?=[ ._-]web[ ._-]?(dl|rip)\\b)/i', score=80), PreferredWord(term='/\\b(amzn|amazon)\\b(?=[ ._-]web[ ._-]?(dl|rip)\\b)/i', score=70), PreferredWord(term='/\\b(nf|netflix)\\b(?=[ ._-]web[ ._-]?(dl|rip)\\b)/i', score=60), PreferredWord(term='/\\b(pcok|Peacock TV)\\b(?=[ ._-]web[ ._-]?(dl|rip)\\b)/i', score=60), PreferredWord(term='/\\b(pmtp)\\b(?=[ ._-]web[ ._-]?(dl|rip)\\b)/i', score=60), PreferredWord(term='/\\b(stan)\\b(?=[ ._-]web[ ._-]?(dl|rip)\\b)/i', score=60), PreferredWord(term='/\\b(4OD)\\b(?=[ ._-]web[ ._-]?(dl|rip)\\b)/i', score=50), PreferredWord(term='/\\b(ALL4)\\b(?=[ ._-]web[ ._-]?(dl|rip)\\b)/i', score=50), PreferredWord(term='/\\b(cc)\\b(?=[ ._-]web[ ._-]?(dl|rip)\\b)/i', score=50), PreferredWord(term='/\\b(crav(e)?)\\b[ ._-]web[ ._-]?(dl|rip)?\\b/i', score=50), PreferredWord(term='/\\b(dcu)\\b(?=[ ._-]web[ ._-]?(dl|rip)\\b)/i', score=50), PreferredWord(term='/\\b(fod)\\b(?=[ ._-]web[ ._-]?(dl|rip)\\b)/i', score=50), PreferredWord(term='/\\b(hbo)(?![ ._-]max)\\b(?=[ ._-]web[ ._-]?(dl|rip)\\b)/i', score=50), PreferredWord(term='/\\b(hulu)\\b(?=[ ._-]web[ ._-]?(dl|rip)\\b)/i', score=50), PreferredWord(term='/\\b(it)\\b(?=[ ._-]web[ ._-]?(dl|rip)\\b)/i', score=50), PreferredWord(term='/\\b(nlz)\\b(?=[ ._-]web[ ._-]?(dl|rip)\\b)/i', score=50), PreferredWord(term='/\\b(ovid)\\b(?=[ ._-]web[ ._-]?(dl|rip)\\b)/i', score=50), PreferredWord(term='/\\b(red)\\b(?=[ ._-]web[ ._-]?(dl|rip)\\b)/i', score=50), PreferredWord(term='/\\b(sho|showtime)\\b(?=[ ._-]web[ ._-]?(dl|rip)\\b)/i', score=50), PreferredWord(term='/\\b(tver)\\b(?=[ ._-]web[ ._-]?(dl|rip)\\b)/i', score=50), PreferredWord(term='/\\b(u-next)\\b(?=[ ._-]web[ ._-]?(dl|rip)\\b)/i', score=50), PreferredWord(term='/\\b(vdl)\\b(?=[ ._-]web[ ._-]?(dl|rip)\\b)/i', score=50)] -> (created)
2023-12-01T03:20:50.324325040Z 2023-11-30 22:20:50,324 buildarr:1 buildarr.config.base [INFO] <sonarr> (default) sonarr.settings.profiles.release_profiles.definitions['Release Sources (Streaming Service)'].include_preferred_when_renaming: False -> (created)
2023-12-01T03:20:50.324545796Z 2023-11-30 22:20:50,324 buildarr:1 buildarr.config.base [INFO] <sonarr> (default) sonarr.settings.profiles.release_profiles.definitions['Release Sources (Streaming Service)'].indexer: None -> (created)
2023-12-01T03:20:50.324709726Z 2023-11-30 22:20:50,324 buildarr:1 buildarr.config.base [INFO] <sonarr> (default) sonarr.settings.profiles.release_profiles.definitions['Release Sources (Streaming Service)'].tags: set() -> (created)
2023-12-01T03:20:50.380406521Z 2023-11-30 22:20:50,378 buildarr:1 buildarr.cli.daemon [ERROR] <sonarr> (default) An error occurred while applying initial configuration: Unexpected response with status code 200 from 'POST http://sonarr:8989/api/v3/releaseprofile':
2023-12-01T03:20:50.380419475Z Traceback (most recent call last):
2023-12-01T03:20:50.380422750Z   File "/usr/local/lib/python3.11/site-packages/buildarr/cli/daemon.py", line 215, in _initial_run
2023-12-01T03:20:50.380425542Z     run_apply()
2023-12-01T03:20:50.380428020Z   File "/usr/local/lib/python3.11/site-packages/buildarr/cli/run.py", line 248, in _run
2023-12-01T03:20:50.380430499Z     if manager.update_remote(
2023-12-01T03:20:50.380432870Z        ^^^^^^^^^^^^^^^^^^^^^^
2023-12-01T03:20:50.380435518Z   File "/usr/local/lib/python3.11/site-packages/buildarr/manager/__init__.py", line 192, in update_remote
2023-12-01T03:20:50.380446741Z     return local_instance_config.update_remote(
2023-12-01T03:20:50.380449450Z            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-12-01T03:20:50.380451894Z   File "/usr/local/lib/python3.11/site-packages/buildarr/config/base.py", line 272, in update_remote
2023-12-01T03:20:50.380454381Z     if isinstance(field, ConfigBase) and field.update_remote(
2023-12-01T03:20:50.380456801Z                                          ^^^^^^^^^^^^^^^^^^^^
2023-12-01T03:20:50.380459198Z   File "/usr/local/lib/python3.11/site-packages/buildarr_sonarr/config/__init__.py", line 116, in update_remote
2023-12-01T03:20:50.380486626Z     self.profiles.update_remote(
2023-12-01T03:20:50.380492305Z   File "/usr/local/lib/python3.11/site-packages/buildarr/config/base.py", line 272, in update_remote
2023-12-01T03:20:50.380495008Z     if isinstance(field, ConfigBase) and field.update_remote(
2023-12-01T03:20:50.380497378Z                                          ^^^^^^^^^^^^^^^^^^^^
2023-12-01T03:20:50.380499800Z   File "/usr/local/lib/python3.11/site-packages/buildarr_sonarr/config/profiles/release.py", line 438, in update_remote
2023-12-01T03:20:50.380502389Z     profile._create_remote(
2023-12-01T03:20:50.380504742Z   File "/usr/local/lib/python3.11/site-packages/buildarr_sonarr/config/profiles/release.py", line 333, in _create_remote
2023-12-01T03:20:50.380507224Z     api_post(
2023-12-01T03:20:50.380509572Z   File "/usr/local/lib/python3.11/site-packages/buildarr_sonarr/api.py", line 182, in api_post
2023-12-01T03:20:50.380512035Z     api_error(method="POST", url=url, response=res)
2023-12-01T03:20:50.380514528Z   File "/usr/local/lib/python3.11/site-packages/buildarr_sonarr/api.py", line 307, in api_error
2023-12-01T03:20:50.380517004Z     raise SonarrAPIError(error_message, status_code=response.status_code)
2023-12-01T03:20:50.380519896Z buildarr_sonarr.exceptions.SonarrAPIError: Unexpected response with status code 200 from 'POST http://sonarr:8989/api/v3/releaseprofile':
2023-12-01T03:20:50.380742341Z 2023-11-30 22:20:50,380 buildarr:1 buildarr.cli.daemon [WARNING] Aborted applying initial configuration
2023-12-01T03:20:50.381137854Z 2023-11-30 22:20:50,381 buildarr:1 buildarr.cli.daemon [INFO] Setting up signal handlers
2023-12-01T03:20:50.381343189Z 2023-11-30 22:20:50,381 buildarr:1 buildarr.cli.daemon [INFO] Finished setting up signal handlers
2023-12-01T03:20:50.381538353Z 2023-11-30 22:20:50,381 buildarr:1 buildarr.cli.daemon [INFO] The next run will be at 2023-12-01 03:00
2023-12-01T03:20:50.381691430Z 2023-11-30 22:20:50,381 buildarr:1 buildarr.cli.daemon [INFO] Buildarr ready.
```

Anything obvious i'm doing wrong?

**Comment by ajyey** [comment]
I've also tried with a host value of `localhost` and got the same result unfortunately

**Comment by Callum027** [comment]
I have tested my local Sonarr v3 installation. The expected status code is `201 Accepted`, but your installation appears to be returning `200 OK` (and not returning the created release profile in the results).

Buildarr's connection test for the Sonarr API is succeeding so it should be working as expected.

There isn't much more I can say at the moment without getting more information about what exact Sonarr version your setup is using, and the current configuration for it.

**Comment by ajyey** [comment]
Apologies I meant to include the sonarr version in my original post. Here are my versions directly from the sonarr settings page

Version
    3.0.10.1567

Package Version
    3.0.10.1567-ls214 by [linuxserver.io](https://linuxserver.io/) 

Mono Version
    6.12.0.200

**Comment by Callum027** [comment]
That helps very much, thanks.

You appear to have `/sonarr` defined as your URL base. And it looks like I neglected to add the capability to configure that for the *Arr instances themselves.

In addition, the connection test does not seem to take into account that the URL base was changed. This is a bug that needs to be fixed.

I'll get started on a fix for the next release.

**Comment by ajyey** [comment]
Thanks for prompt reply! Sounds good. 

Would modifying the base url to just be / get me unblocked ?

**Comment by Callum027** [comment]
> Thanks for prompt reply! Sounds good.
> 
> Would modifying the base url to just be / get me unblocked ?

EIther that or setting it to an empty value should, yes.

**Comment by ajyey** [comment]
I can confirm that setting the base URL to `/` worked in my case. 

Thank you!

**Comment by Callum027** [comment]
Added the following to all Buildarr plugins:

* Specifying the URL base for instances as the `url_base` host configuration attribute
* Using the provided URL path as the URL base when dumping instance configurations
