### ISSUE TITLE
error occurred while applying initial configuration: 1 validation error for RadarrApplication

### ISSUE THREAD

**Issue by ezekieldas** [buildarr/buildarr#193]
Hello --I'm very excited about your project. I'd really like to get this working. 

I'm unsure if this is a bug or something amiss in my configuration. What really puzzles me is the mention of `RadarrApplication api_key` here because Radarr is entirely absent in the config + I've disabled prowlarr -> settings -> applications -> radarr. 

I see this might be coming from here ([buildarr-prowlarr](https://github.com/buildarr/buildarr-prowlarr/blob/8e67cc40a4e4d6035607fd5908fe0f46add6ac64/buildarr_prowlarr/config/settings/apps/applications.py#L336)) but the comment isn't clear to me:

        There is a [Radarr plugin for Buildarr](https://buildarr.github.io/plugins/radarr)
        that can be used to link Radarr instances with Prowlarr using the `instance_name`
        attribute.

<details><summary>buildarr.yml</summary>

Anyhow, here are my configs/logs:

```
prowlarr:
  hostname: "prowlarr.somewhere.io"
  port: 9696
  protocol: "http"
  api_key: "foobar"
```

</details>

<details><summary>buildarr log</summary>

```
2024-04-20 10:53:15,844 buildarr:1 buildarr.cli.run [INFO] Finished performing post-initialisation configuration render
2024-04-20 10:53:15,844 buildarr:1 buildarr.cli.run [INFO] Updating configuration on remote instances
2024-04-20 10:53:15,845 buildarr:1 buildarr.cli.run [INFO] <prowlarr> (default) Fetching remote configuration to check if updates are required
2024-04-20 10:53:15,993 buildarr:1 buildarr.cli.daemon [ERROR] <prowlarr> (default) An error occurred while applying initial configuration: 1 validation error for RadarrApplication
api_key
  ensure this value has at least 32 characters (type=value_error.any_str.min_length; limit_value=32)
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/buildarr/cli/daemon.py", line 215, in _initial_run
    run_apply()
  File "/usr/local/lib/python3.11/site-packages/buildarr/cli/run.py", line 235, in _run
    remote_instance_config = manager.from_remote(instance_config, instance_secrets)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/buildarr/manager/__init__.py", line 171, in from_remote
    return instance_config.from_remote(secrets)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/buildarr_prowlarr/config/__init__.py", line 169, in from_remote
    settings=ProwlarrSettings.from_remote(secrets),
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/buildarr/config/base.py", line 85, in from_remote
    fields[field_name] = field.type_.from_remote(secrets)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/buildarr/config/base.py", line 85, in from_remote
    fields[field_name] = field.type_.from_remote(secrets)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/buildarr_prowlarr/config/settings/apps/applications.py", line 695, in from_remote
    definitions={
                ^
  File "/usr/local/lib/python3.11/site-packages/buildarr_prowlarr/config/settings/apps/applications.py", line 698, in <dictcomp>
    ]._from_remote(
      ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/buildarr_prowlarr/config/settings/apps/applications.py", line 178, in _from_remote
    return cls(
           ^^^^
  File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for RadarrApplication
api_key
  ensure this value has at least 32 characters (type=value_error.any_str.min_length; limit_value=32)
2024-04-20 10:53:15,996 buildarr:1 buildarr.cli.daemon [WARNING] Aborted applying initial configuration
2024-04-20 10:53:15,999 buildarr:1 buildarr.cli.daemon [INFO] Setting up signal handlers
2024-04-20 10:53:15,999 buildarr:1 buildarr.cli.daemon [INFO] Finished setting up signal handlers
2024-04-20 10:53:15,999 buildarr:1 buildarr.cli.daemon [INFO] The next run will be at 2024-04-21 03:00
2024-04-20 10:53:15,999 buildarr:1 buildarr.cli.daemon [INFO] Buildarr ready.
```
</details>

<details><summary>prowlar trace log</summary>

```
2024-04-20 10:53:15.8|Trace|Http|Req: 52 [GET] /initialize.json (from 172.26.0.1 python-requests/2.31.0)
2024-04-20 10:53:15.8|Trace|Http|Res: 52 [GET] /initialize.json: 200.OK (1 ms)
2024-04-20 10:53:15.8|Trace|Http|Req: 53 [GET] /api/v1/system/status (from 172.26.0.1 prowlarr-py/v0.4.1)
2024-04-20 10:53:15.8|Debug|Prowlarr.Http.Authentication.ApiKeyAuthenticationHandler|AuthenticationScheme: API was successfully authenticated.
2024-04-20 10:53:15.8|Trace|Http|Res: 53 [GET] /api/v1/system/status: 200.OK (2 ms)
2024-04-20 10:53:15.8|Debug|Api|[GET] /api/v1/system/status: 200.OK (2 ms)
2024-04-20 10:53:15.8|Trace|Http|Req: 54 [GET] /api/v1/indexer (from 172.26.0.1 prowlarr-py/v0.4.1)
2024-04-20 10:53:15.8|Debug|Prowlarr.Http.Authentication.ApiKeyAuthenticationHandler|AuthenticationScheme: API was successfully authenticated.
2024-04-20 10:53:15.8|Trace|Http|Res: 54 [GET] /api/v1/indexer: 200.OK (9 ms)
2024-04-20 10:53:15.8|Debug|Api|[GET] /api/v1/indexer: 200.OK (9 ms)
2024-04-20 10:53:15.8|Trace|Http|Req: 55 [GET] /api/v1/appprofile (from 172.26.0.1 prowlarr-py/v0.4.1)
2024-04-20 10:53:15.8|Debug|Prowlarr.Http.Authentication.ApiKeyAuthenticationHandler|AuthenticationScheme: API was successfully authenticated.
2024-04-20 10:53:15.8|Trace|Http|Res: 55 [GET] /api/v1/appprofile: 200.OK (1 ms)
2024-04-20 10:53:15.8|Debug|Api|[GET] /api/v1/appprofile: 200.OK (1 ms)
2024-04-20 10:53:15.8|Trace|Http|Req: 56 [GET] /api/v1/indexerproxy (from 172.26.0.1 prowlarr-py/v0.4.1)
2024-04-20 10:53:15.8|Debug|Prowlarr.Http.Authentication.ApiKeyAuthenticationHandler|AuthenticationScheme: API was successfully authenticated.
2024-04-20 10:53:15.9|Trace|Http|Res: 56 [GET] /api/v1/indexerproxy: 200.OK (2 ms)
2024-04-20 10:53:15.9|Debug|Api|[GET] /api/v1/indexerproxy: 200.OK (2 ms)
2024-04-20 10:53:15.9|Trace|Http|Req: 57 [GET] /api/v1/applications/schema (from 172.26.0.1 prowlarr-py/v0.4.1)
2024-04-20 10:53:15.9|Debug|Prowlarr.Http.Authentication.ApiKeyAuthenticationHandler|AuthenticationScheme: API was successfully authenticated.
2024-04-20 10:53:15.9|Trace|Http|Res: 57 [GET] /api/v1/applications/schema: 200.OK (4 ms)
2024-04-20 10:53:15.9|Debug|Api|[GET] /api/v1/applications/schema: 200.OK (4 ms)
2024-04-20 10:53:15.9|Trace|Http|Req: 58 [GET] /api/v1/applications (from 172.26.0.1 prowlarr-py/v0.4.1)
2024-04-20 10:53:15.9|Debug|Prowlarr.Http.Authentication.ApiKeyAuthenticationHandler|AuthenticationScheme: API was successfully authenticated.
2024-04-20 10:53:15.9|Trace|Http|Res: 58 [GET] /api/v1/applications: 200.OK (3 ms)
2024-04-20 10:53:15.9|Debug|Api|[GET] /api/v1/applications: 200.OK (3 ms)
2024-04-20 10:53:32.2|Trace|Scheduler|Pending Tasks: 0
```

**Comment by Callum027** [comment]
Hi @ezekieldas, thanks for trying Buildarr.

Regarding Sonarr V4, I've got some refactors to do before I can work on that, but I'll do my best to get it out as soon as I can.

As for your issue here:

```
  File "/usr/local/lib/python3.11/site-packages/buildarr_prowlarr/config/settings/apps/applications.py", line 178, in _from_remote
    return cls(
           ^^^^
  File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for SonarrApplication
api_key
  ensure this value has at least 32 characters (type=value_error.any_str.min_length; limit_value=32)
```

These errors are coming from the Prowlarr plugin (unfortunately it's not as clear as it could have been). When configuring a [Sonarr or Radarr application](https://buildarr.github.io/plugins/prowlarr/configuration/settings/apps/applications/#sonarr), there are two ways of doing it:

1. Linking Prowlarr with a Buildarr-managed Sonarr instance. In this case, define the `instance_name` attribute to tell Buildarr which Sonarr instance to connect.
1. Configuring Prowlarr with a non-Buildarr-managed Sonarr instance. In this case, you need to explicitly specify the `api_key` for that Sonarr instance.

Since you're managing your Sonarr and Radarr instances using Buildarr, please make sure to set `instance_name` on the application definitions (if they don't have an explicit name, use `default` here).

For example, if you're defining the Sonarr and Radarr instances like so in Buildarr:

```yaml
sonarr:
  hostname: "sonarr.somewhere.io"
  port: 8989
  protocol: "http"
  api_key: "foobar"
  settings:
    ...
 
 radarr:
  hostname: "sonarr.somewhere.io"
  port: 7878
  protocol: "http"
  api_key: "foobar"
  settings:
    ...
```

For the Prowlarr application definitions, you'd do this:

```
prowlarr:
  hostname: "prowlarr.somewhere.io"
  port: 9696
  protocol: "http"
  api_key: "foobar"
  settings:
    apps:
      applications:
        definitions:
          Sonarr:
            type: sonarr
            instance_name: default  # The default Sonarr instance.
            base_url: http://sonarr:8989
            prowlarr_url: http://prowlarr:9696
          Radarr:
            type: radarr
            instance_name: default  # The default Radarr instance.
            base_url: http://radarr:7878
            prowlarr_url: http://prowlarr:9696
```

**Comment by Callum027** [comment]
> ValueError: 'value' attribute not included for remote field 'tvDirectory' and 'field_default' not defined in local attribute

Unfortunately, this is a bug with the Sonarr plugin and how it currently handles attribute values that are not returned by the Sonarr API.

I am assuming you have a download client configured in your Sonarr instance. I have two questions:

* What kind of download client do you have configured?
* Could you please set the "Directory" attribute on the download client to a non-empty value, and then clear it (set it to be empty), to see if that resolves the issue?

**Comment by Callum027** [comment]
@ezekieldas, if you have a Discord account, I created a Discord server so we can discuss things further, if you like. Doing this via GitHub is a bit problematic.

https://discord.gg/JzVV42nt

**Comment by Callum027** [comment]
That's great! Yeah, unfortunately testing pre-existing configuration like is very difficult for me, so issues like these manage to get through. I'm working on unit tests that will hopefully allow me to catch issues like this in the future.

Buildarr tends to work better when you start off with a brand new instance and let *it* do the configuring, at least for now.

**Comment by Callum027** [comment]
Thanks @ezekieldas, I have enabled Discussions on this repository. Hopefully that makes it easier for people to get help.
