### ISSUE TITLE
Issue when running dump-config

### ISSUE THREAD

**Issue by nothing2obvi** [buildarr/buildarr#219]
On startup, just having configured Sonarr in the `buildarr.yml` file, I get the following:

```
5/14/2024
03:11:25 PM
2024-05-14 22:11:25,626 buildarr:1 buildarr.cli.run [INFO] Updating configuration on remote instances
05/14/2024
03:11:25 PM
2024-05-14 22:11:25,626 buildarr:1 buildarr.cli.run [INFO] <sonarr> (default) Fetching remote configuration to check if updates are required
05/14/2024
03:11:26 PM
2024-05-14 22:11:26,042 buildarr:1 buildarr.cli.daemon [ERROR] <sonarr> (default) An error occurred while applying initial configuration: 'preferred'
05/14/2024
03:11:26 PM
Traceback (most recent call last):
05/14/2024
03:11:26 PM
  File "/usr/local/lib/python3.11/site-packages/buildarr/cli/daemon.py", line 215, in _initial_run
05/14/2024
03:11:26 PM
    run_apply()
05/14/2024
03:11:26 PM
  File "/usr/local/lib/python3.11/site-packages/buildarr/cli/run.py", line 235, in _run
05/14/2024
03:11:26 PM
    remote_instance_config = manager.from_remote(instance_config, instance_secrets)
05/14/2024
03:11:26 PM
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
05/14/2024
03:11:26 PM
  File "/usr/local/lib/python3.11/site-packages/buildarr/manager/__init__.py", line 171, in from_remote
05/14/2024
03:11:26 PM
    return instance_config.from_remote(secrets)
05/14/2024
03:11:26 PM
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
05/14/2024
03:11:26 PM
  File "/usr/local/lib/python3.11/site-packages/buildarr_sonarr/config/__init__.py", line 340, in from_remote
05/14/2024
03:11:26 PM
    settings=SonarrSettingsConfig.from_remote(secrets),
05/14/2024
03:11:26 PM
2024-05-14 22:11:26,047 buildarr:1 buildarr.cli.daemon [INFO] Setting up signal handlers
05/14/2024
03:11:26 PM
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
05/14/2024
03:11:26 PM
  File "/usr/local/lib/python3.11/site-packages/buildarr/config/base.py", line 85, in from_remote
05/14/2024
03:11:26 PM
    fields[field_name] = field.type_.from_remote(secrets)
05/14/2024
03:11:26 PM
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
05/14/2024
03:11:26 PM
  File "/usr/local/lib/python3.11/site-packages/buildarr/config/base.py", line 85, in from_remote
05/14/2024
03:11:26 PM
    fields[field_name] = field.type_.from_remote(secrets)
05/14/2024
03:11:26 PM
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
05/14/2024
03:11:26 PM
  File "/usr/local/lib/python3.11/site-packages/buildarr_sonarr/config/profiles/release.py", line 405, in from_remote
05/14/2024
03:11:26 PM
    definitions={
05/14/2024
03:11:26 PM
                ^
05/14/2024
03:11:26 PM
  File "/usr/local/lib/python3.11/site-packages/buildarr_sonarr/config/profiles/release.py", line 406, in <dictcomp>
05/14/2024
03:11:26 PM
    profile["name"]: ReleaseProfile._from_remote(indexer_ids, tag_ids, profile)
05/14/2024
03:11:26 PM
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
05/14/2024
03:11:26 PM
  File "/usr/local/lib/python3.11/site-packages/buildarr_sonarr/config/profiles/release.py", line 253, in _from_remote
05/14/2024
03:11:26 PM
    return cls(**cls.get_local_attrs(cls._get_remote_map(indexer_ids, tag_ids), remote_attrs))
05/14/2024
03:11:26 PM
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
05/14/2024
03:11:26 PM
  File "/usr/local/lib/python3.11/site-packages/buildarr/config/base.py", line 234, in get_local_attrs
05/14/2024
03:11:26 PM
    remote_attr = remote_attrs[remote_attr_name]
05/14/2024
03:11:26 PM
                  ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
05/14/2024
03:11:26 PM
KeyError: 'preferred'
05/14/2024
03:11:26 PM
2024-05-14 22:11:26,047 buildarr:1 buildarr.cli.daemon [WARNING] Aborted applying initial configuration
05/14/2024
03:11:26 PM
2024-05-14 22:11:26,048 buildarr:1 buildarr.cli.daemon [INFO] Finished setting up signal handlers
05/14/2024
03:11:26 PM
2024-05-14 22:11:26,048 buildarr:1 buildarr.cli.daemon [INFO] The next run will be at 2024-05-19 05:00
05/14/2024
03:11:26 PM
2024-05-14 22:11:26,048 buildarr:1 buildarr.cli.daemon [INFO] Buildarr ready.
```

And on `dump-config` for Sonarr I get the following, even after entering my API key:
```
Traceback (most recent call last):
  File "/usr/local/bin/buildarr", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/buildarr_sonarr/cli.py", line 94, in dump_config
    .from_remote(
     ^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/buildarr/manager/__init__.py", line 171, in from_remote
    return instance_config.from_remote(secrets)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/buildarr_sonarr/config/__init__.py", line 340, in from_remote
    settings=SonarrSettingsConfig.from_remote(secrets),
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/buildarr/config/base.py", line 85, in from_remote
    fields[field_name] = field.type_.from_remote(secrets)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/buildarr/config/base.py", line 85, in from_remote
    fields[field_name] = field.type_.from_remote(secrets)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/buildarr_sonarr/config/profiles/release.py", line 405, in from_remote
    definitions={
                ^
  File "/usr/local/lib/python3.11/site-packages/buildarr_sonarr/config/profiles/release.py", line 406, in <dictcomp>
    profile["name"]: ReleaseProfile._from_remote(indexer_ids, tag_ids, profile)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/buildarr_sonarr/config/profiles/release.py", line 253, in _from_remote
    return cls(**cls.get_local_attrs(cls._get_remote_map(indexer_ids, tag_ids), remote_attrs))
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/buildarr/config/base.py", line 234, in get_local_attrs
    remote_attr = remote_attrs[remote_attr_name]
                  ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
KeyError: 'preferred'
```

I was going to try without authentication enabled but apparently Sonarr now requires it.

**Comment by bogorad** [comment]
same problem here. when used with -k <key> I get the same error.

**Comment by skwort** [comment]
I ran into this same issue today and dug into it further.

From what I can tell, the problem stems from the `remote_map` in `buildarr-sonarr/config/profiles/release.py`, which defines how Buildarr maps Sonarr's API fields to internal attributes. In my configuration, I have the following release profile:

![Image](https://github.com/user-attachments/assets/77bbed7c-0c00-4e06-870b-f895e3c4ba0f)

When Buildarr queries the API, it receives the following response for `remote_attrs`:
```python
{
    'name': 'Anime filter',
    'enabled': True,
    'required': ['Multi-Subs'],
    'ignored': ['.ts', 'VOSTFR', '.mp4', 'español', 'Español', 'CHT'],
    'indexerId': 0,
    'tags': [1],
    'id': 1
}
```
Comparing this response to the expected fields in remote_map, we see that the `"preferred"` key (highlighted below) is missing.
```diff
buildarr-sonarr/config/profiles/release.py
def _get_remote_map(
        cls,
        indexer_ids: Mapping[str, int],
        tag_ids: Mapping[str, int],
    ) -> List[RemoteMapEntry]:
        return [
            ("enable", "enabled", {}),
            ("must_contain", "required", {"encoder": lambda v: sorted(v)}),
            ("must_not_contain", "ignored", {"encoder": lambda v: sorted(v)}),
            (
+                "preferred",
+                "preferred",
                {
                    "decoder": lambda v: [
                        PreferredWord(term=p["key"], score=p["value"]) for p in v
                    ],
                    "encoder": lambda v: [{"key": p.term, "value": p.score} for p in v],
                },
            ),
            ("include_preferred_when_renaming", "includePreferredWhenRenaming", {}),
            (
                "indexer",
                "indexerId",
                {
                    "decoder": lambda v: next(
                        (ind for ind, ind_id in indexer_ids.items() if ind_id == v),
                        None,
                    ),
                    "encoder": lambda v: indexer_ids[v] if v else 0,
                },
            ),
            (
                "tags",
                "tags",
                {
                    "decoder": lambda v: set(
                        (tag for tag, tag_id in tag_ids.items() if tag_id in v),
                    ),
                    "encoder": lambda v: sorted(tag_ids[tag] for tag in v),
                },
            ),
        ]
```
Since the `"preferred"` key doesn't exist in Sonarr's API response, this causes a `KeyError` in Buildarr when it tries to access it.

To confirm this, I temporarily removed the `"preferred"` mapping from `remote_map`, which led to another `KeyError`—this time for `"includePreferredWhenRenaming"`. Removing both of these mappings allowed Buildarr to function correctly without crashing.

I'll open a pull request with the fix tomorrow.
