### ISSUE TITLE
Error with localhost as hostname

### ISSUE THREAD

**Issue by raverydavis** [buildarr/buildarr#223]
I can't see why this isn't working, here's my compose and configuration (maybe because I'm using linuxserver docker images?)

```
services:
  sonarr:
    container_name: sonarr
    hostname: sonarr
    image: ghcr.io/linuxserver/sonarr:latest
    restart: unless-stopped
    ports:
      - 8989:8989
    environment:
      PUID: "1000"
      PGID: "1000"
    volumes:
      - ../data/media/tvshows:/tvshows
      - ../data/media/downloads:/downloads
      - ./data/sonarr:/config

  buildarr:
    container_name: buildarr
    image: callum027/buildarr:latest
    restart: unless-stopped
    volumes:
      - ./data/buildarr:/config
    environment:
      PUID: "1000"
      PGID: "1000"
    depends_on:
      - sonarr
````

buildarr.yml
```
buildarr:
  watch_config: true

# Sonarr instance configuration
sonarr:
  hostname: "localhost"
  port: 8989
  protocol: "http"
  settings:
    # General settings (all options supported except for changing the API key)
    general:
      host:
        instance_name: "Sonarr (Buildarr Example)"
```

Error logs
```
2024-07-09 16:11:57 2024-07-09 23:11:57,538 buildarr:1 buildarr.cli.daemon [INFO] Buildarr version 0.7.1 (log level: INFO)
2024-07-09 16:11:57 2024-07-09 23:11:57,538 buildarr:1 buildarr.cli.daemon [INFO] Loading configuration file '/config/buildarr.yml'
2024-07-09 16:11:57 2024-07-09 23:11:57,544 buildarr:1 buildarr.cli.daemon [INFO] Finished loading configuration file
2024-07-09 16:11:57 2024-07-09 23:11:57,544 buildarr:1 buildarr.cli.daemon [INFO] Daemon configuration:
2024-07-09 16:11:57 2024-07-09 23:11:57,544 buildarr:1 buildarr.cli.daemon [INFO]  - Watch configuration files: Yes
2024-07-09 16:11:57 2024-07-09 23:11:57,544 buildarr:1 buildarr.cli.daemon [INFO]  - Configuration files to watch:
2024-07-09 16:11:57 2024-07-09 23:11:57,544 buildarr:1 buildarr.cli.daemon [INFO]    - /config/buildarr.yml
2024-07-09 16:11:57 2024-07-09 23:11:57,544 buildarr:1 buildarr.cli.daemon [INFO]  - Update at:
2024-07-09 16:11:57 2024-07-09 23:11:57,545 buildarr:1 buildarr.cli.daemon [INFO]    - Monday 03:00
2024-07-09 16:11:57 2024-07-09 23:11:57,545 buildarr:1 buildarr.cli.daemon [INFO]    - Tuesday 03:00
2024-07-09 16:11:57 2024-07-09 23:11:57,545 buildarr:1 buildarr.cli.daemon [INFO]    - Wednesday 03:00
2024-07-09 16:11:57 2024-07-09 23:11:57,545 buildarr:1 buildarr.cli.daemon [INFO]    - Thursday 03:00
2024-07-09 16:11:57 2024-07-09 23:11:57,545 buildarr:1 buildarr.cli.daemon [INFO]    - Friday 03:00
2024-07-09 16:11:57 2024-07-09 23:11:57,545 buildarr:1 buildarr.cli.daemon [INFO]    - Saturday 03:00
2024-07-09 16:11:57 2024-07-09 23:11:57,545 buildarr:1 buildarr.cli.daemon [INFO]    - Sunday 03:00
2024-07-09 16:11:57 2024-07-09 23:11:57,545 buildarr:1 buildarr.cli.daemon [INFO] Scheduling update jobs
2024-07-09 16:11:57 2024-07-09 23:11:57,545 buildarr:1 buildarr.cli.daemon [INFO] Finished scheduling update jobs
2024-07-09 16:11:57 2024-07-09 23:11:57,545 buildarr:1 buildarr.cli.daemon [INFO] Enabling config file monitoring
2024-07-09 16:11:57 2024-07-09 23:11:57,545 buildarr:1 buildarr.cli.daemon [INFO] Finished enabling config file monitoring
2024-07-09 16:11:57 2024-07-09 23:11:57,545 buildarr:1 buildarr.cli.daemon [INFO] Applying initial configuration
2024-07-09 16:11:57 2024-07-09 23:11:57,546 buildarr:1 buildarr.cli.run [INFO] Loaded plugins: jellyseerr (0.3.2), prowlarr (0.5.1), radarr (0.2.5), sonarr (0.6.4)
2024-07-09 16:11:57 2024-07-09 23:11:57,546 buildarr:1 buildarr.cli.run [INFO] Loading instance configurations
2024-07-09 16:11:57 2024-07-09 23:11:57,546 buildarr:1 buildarr.cli.run [INFO] Finished loading instance configurations
2024-07-09 16:11:57 2024-07-09 23:11:57,546 buildarr:1 buildarr.cli.run [INFO] Running with plugins: sonarr
2024-07-09 16:11:57 2024-07-09 23:11:57,546 buildarr:1 buildarr.cli.run [INFO] Resolving instance dependencies
2024-07-09 16:11:57 2024-07-09 23:11:57,546 buildarr:1 buildarr.cli.run [INFO] Finished resolving instance dependencies
2024-07-09 16:11:57 2024-07-09 23:11:57,546 buildarr:1 buildarr.cli.run [INFO] Rendering instance configuration dynamic attributes
2024-07-09 16:11:57 2024-07-09 23:11:57,546 buildarr:1 buildarr.cli.run [INFO] Finished rendering instance configuration dynamic attributes
2024-07-09 16:11:57 2024-07-09 23:11:57,546 buildarr:1 buildarr.cli.run [INFO] <sonarr> (default) Fetching instance secrets
2024-07-09 16:11:57 2024-07-09 23:11:57,549 buildarr:1 buildarr.cli.daemon [INFO] Setting up signal handlers
2024-07-09 16:11:57 2024-07-09 23:11:57,549 buildarr:1 buildarr.cli.daemon [INFO] Finished setting up signal handlers
2024-07-09 16:11:57 2024-07-09 23:11:57,549 buildarr:1 buildarr.cli.daemon [INFO] The next run will be at 2024-07-10 03:00
2024-07-09 16:11:57 2024-07-09 23:11:57,549 buildarr:1 buildarr.cli.daemon [INFO] Buildarr ready.
2024-07-09 16:11:57 2024-07-09 23:11:57,547 buildarr:1 buildarr.cli.daemon [ERROR] <sonarr> (default) An error occurred while applying initial configuration: HTTPConnectionPool(host='localhost', port=8989): Max retries exceeded with url: /initialize.js (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xffffa2abe490>: Failed to establish a new connection: [Errno 111] Connection refused'))
2024-07-09 16:11:57 Traceback (most recent call last):
2024-07-09 16:11:57   File "/usr/local/lib/python3.11/site-packages/urllib3/connection.py", line 198, in _new_conn
2024-07-09 16:11:57     sock = connection.create_connection(
2024-07-09 16:11:57            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-07-09 16:11:57   File "/usr/local/lib/python3.11/site-packages/urllib3/util/connection.py", line 85, in create_connection
2024-07-09 16:11:57     raise err
2024-07-09 16:11:57   File "/usr/local/lib/python3.11/site-packages/urllib3/util/connection.py", line 73, in create_connection
2024-07-09 16:11:57     sock.connect(sa)
2024-07-09 16:11:57 ConnectionRefusedError: [Errno 111] Connection refused
2024-07-09 16:11:57 
2024-07-09 16:11:57 The above exception was the direct cause of the following exception:
2024-07-09 16:11:57 
2024-07-09 16:11:57 Traceback (most recent call last):
2024-07-09 16:11:57   File "/usr/local/lib/python3.11/site-packages/urllib3/connectionpool.py", line 793, in urlopen
2024-07-09 16:11:57     response = self._make_request(
2024-07-09 16:11:57                ^^^^^^^^^^^^^^^^^^^
2024-07-09 16:11:57   File "/usr/local/lib/python3.11/site-packages/urllib3/connectionpool.py", line 496, in _make_request
2024-07-09 16:11:57     conn.request(
2024-07-09 16:11:57   File "/usr/local/lib/python3.11/site-packages/urllib3/connection.py", line 400, in request
2024-07-09 16:11:57     self.endheaders()
2024-07-09 16:11:57   File "/usr/local/lib/python3.11/http/client.py", line 1293, in endheaders
2024-07-09 16:11:57     self._send_output(message_body, encode_chunked=encode_chunked)
2024-07-09 16:11:57   File "/usr/local/lib/python3.11/http/client.py", line 1052, in _send_output
2024-07-09 16:11:57     self.send(msg)
2024-07-09 16:11:57   File "/usr/local/lib/python3.11/http/client.py", line 990, in send
2024-07-09 16:11:57     self.connect()
2024-07-09 16:11:57   File "/usr/local/lib/python3.11/site-packages/urllib3/connection.py", line 238, in connect
2024-07-09 16:11:57     self.sock = self._new_conn()
2024-07-09 16:11:57                 ^^^^^^^^^^^^^^^^
2024-07-09 16:11:57   File "/usr/local/lib/python3.11/site-packages/urllib3/connection.py", line 213, in _new_conn
2024-07-09 16:11:57     raise NewConnectionError(
2024-07-09 16:11:57 urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0xffffa2abe490>: Failed to establish a new connection: [Errno 111] Connection refused
2024-07-09 16:11:57 
2024-07-09 16:11:57 The above exception was the direct cause of the following exception:
2024-07-09 16:11:57 
2024-07-09 16:11:57 Traceback (most recent call last):
2024-07-09 16:11:57   File "/usr/local/lib/python3.11/site-packages/requests/adapters.py", line 486, in send
2024-07-09 16:11:57     resp = conn.urlopen(
2024-07-09 16:11:57            ^^^^^^^^^^^^^
2024-07-09 16:11:57   File "/usr/local/lib/python3.11/site-packages/urllib3/connectionpool.py", line 847, in urlopen
2024-07-09 16:11:57     retries = retries.increment(
2024-07-09 16:11:57               ^^^^^^^^^^^^^^^^^^
2024-07-09 16:11:57   File "/usr/local/lib/python3.11/site-packages/urllib3/util/retry.py", line 515, in increment
2024-07-09 16:11:57     raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
2024-07-09 16:11:57     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-07-09 16:11:57 urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=8989): Max retries exceeded with url: /initialize.js (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xffffa2abe490>: Failed to establish a new connection: [Errno 111] Connection refused'))
2024-07-09 16:11:57 
2024-07-09 16:11:57 During handling of the above exception, another exception occurred:
2024-07-09 16:11:57 
2024-07-09 16:11:57 Traceback (most recent call last):
2024-07-09 16:11:57   File "/usr/local/lib/python3.11/site-packages/buildarr/cli/daemon.py", line 215, in _initial_run
2024-07-09 16:11:57     run_apply()
2024-07-09 16:11:57   File "/usr/local/lib/python3.11/site-packages/buildarr/cli/run.py", line 208, in _run
2024-07-09 16:11:57     instance_secrets: SecretsPlugin = state.plugins[plugin_name].secrets.get(
2024-07-09 16:11:57                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-07-09 16:11:57   File "/usr/local/lib/python3.11/site-packages/buildarr_sonarr/secrets.py", line 84, in get
2024-07-09 16:11:57     return cls.get_from_url(
2024-07-09 16:11:57            ^^^^^^^^^^^^^^^^^
2024-07-09 16:11:57   File "/usr/local/lib/python3.11/site-packages/buildarr_sonarr/secrets.py", line 110, in get_from_url
2024-07-09 16:11:57     initialize_js = get_initialize_js(host_url)
2024-07-09 16:11:57                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-07-09 16:11:57   File "/usr/local/lib/python3.11/site-packages/buildarr_sonarr/api.py", line 62, in get_initialize_js
2024-07-09 16:11:57     res = requests.get(
2024-07-09 16:11:57           ^^^^^^^^^^^^^
2024-07-09 16:11:57   File "/usr/local/lib/python3.11/site-packages/requests/api.py", line 73, in get
2024-07-09 16:11:57     return request("get", url, params=params, **kwargs)
2024-07-09 16:11:57            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-07-09 16:11:57   File "/usr/local/lib/python3.11/site-packages/requests/api.py", line 59, in request
2024-07-09 16:11:57     return session.request(method=method, url=url, **kwargs)
2024-07-09 16:11:57            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-07-09 16:11:57   File "/usr/local/lib/python3.11/site-packages/requests/sessions.py", line 589, in request
2024-07-09 16:11:57     resp = self.send(prep, **send_kwargs)
2024-07-09 16:11:57            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-07-09 16:11:57   File "/usr/local/lib/python3.11/site-packages/requests/sessions.py", line 703, in send
2024-07-09 16:11:57     r = adapter.send(request, **kwargs)
2024-07-09 16:11:57         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-07-09 16:11:57   File "/usr/local/lib/python3.11/site-packages/requests/adapters.py", line 519, in send
2024-07-09 16:11:57     raise ConnectionError(e, request=request)
2024-07-09 16:11:57 requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=8989): Max retries exceeded with url: /initialize.js (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xffffa2abe490>: Failed to establish a new connection: [Errno 111] Connection refused'))
2024-07-09 16:11:57 2024-07-09 23:11:57,549 buildarr:1 buildarr.cli.daemon [WARNING] Aborted applying initial configuration

```

**Comment by raverydavis** [comment]
Oh did not realize I selected the release template. Anyway, part of the issue appears to be that initialize.js does not exist, it's now http://localhost:8989/initialize.json

**Comment by NelsonDane** [comment]
I think this is a Docker networking issue. "localhost" in your config will refer to the buildarr container since that's what's running your buildarr config. Since your sonarr container is not on the localhost of the buildarr container, then you must use the sonarr IP or the name of the service (sonarr)
