### ISSUE TITLE
Unable to set Prowlarr config when Prowlarr is using Gluetun and Buildarr is using a named hostname of prowlarr

### ISSUE THREAD

**Issue by kylelaverty** [buildarr/buildarr#225]
Currently, I have Prowlarr set to use Gluetun in my docker-compose setup so that the lookups for torrents go through the VPN.

When Buildarr tries to apply any configuration changes to anything using Gluetun it doesn't work and errors out. This is when using the recommended `prowlarr` setting as the hostname. If it is switched with `localhost` then it works.

Here is the current state of my setup via a tag on my repo:
https://github.com/kylelaverty/docker-media-center/tree/v0.5-networking-issue

I have no idea what setup issue I have created but I have done a few different things to try to fix it and the only thing that works (while retaining the named hostname) is moving Prowlarr out from under Gluetun, which is not really an ideal solution.

Any help in figuring this out would be greatly appreciated.

Here is the error I am seeing currently when Buildarr is also using Gluetun and set to use the name alias for Prowlarr:
```
2024-07-22 12:58:22 2024-07-22 12:58:22,888 buildarr:1 buildarr.cli.daemon [INFO] Buildarr version 0.7.1 (log level: INFO)
2024-07-22 12:58:22 2024-07-22 12:58:22,889 buildarr:1 buildarr.cli.daemon [INFO] Loading configuration file '/config/buildarr.yml'
2024-07-22 12:58:23 2024-07-22 12:58:23,060 buildarr:1 buildarr.cli.daemon [INFO] Finished loading configuration file
2024-07-22 12:58:23 2024-07-22 12:58:23,060 buildarr:1 buildarr.cli.daemon [INFO] Daemon configuration:
2024-07-22 12:58:23 2024-07-22 12:58:23,060 buildarr:1 buildarr.cli.daemon [INFO]  - Watch configuration files: Yes
2024-07-22 12:58:23 2024-07-22 12:58:23,060 buildarr:1 buildarr.cli.daemon [INFO]  - Configuration files to watch:
2024-07-22 12:58:23 2024-07-22 12:58:23,060 buildarr:1 buildarr.cli.daemon [INFO]    - /config/buildarr.yml
2024-07-22 12:58:23 2024-07-22 12:58:23,060 buildarr:1 buildarr.cli.daemon [INFO]    - /config/radarr.yml
2024-07-22 12:58:23 2024-07-22 12:58:23,060 buildarr:1 buildarr.cli.daemon [INFO]    - /config/prowlarr.yml
2024-07-22 12:58:23 2024-07-22 12:58:23,060 buildarr:1 buildarr.cli.daemon [INFO]    - /config/prowlarr-settings/prowlarr-indexers.yml
2024-07-22 12:58:23 2024-07-22 12:58:23,060 buildarr:1 buildarr.cli.daemon [INFO]    - /config/prowlarr-settings/prowlarr-tags.yml
2024-07-22 12:58:23 2024-07-22 12:58:23,060 buildarr:1 buildarr.cli.daemon [INFO]  - Update at:
2024-07-22 12:58:23 2024-07-22 12:58:23,060 buildarr:1 buildarr.cli.daemon [INFO]    - Monday 03:00
2024-07-22 12:58:23 2024-07-22 12:58:23,060 buildarr:1 buildarr.cli.daemon [INFO]    - Tuesday 03:00
2024-07-22 12:58:23 2024-07-22 12:58:23,060 buildarr:1 buildarr.cli.daemon [INFO]    - Wednesday 03:00
2024-07-22 12:58:23 2024-07-22 12:58:23,060 buildarr:1 buildarr.cli.daemon [INFO]    - Thursday 03:00
2024-07-22 12:58:23 2024-07-22 12:58:23,060 buildarr:1 buildarr.cli.daemon [INFO]    - Friday 03:00
2024-07-22 12:58:23 2024-07-22 12:58:23,060 buildarr:1 buildarr.cli.daemon [INFO]    - Saturday 03:00
2024-07-22 12:58:23 2024-07-22 12:58:23,061 buildarr:1 buildarr.cli.daemon [INFO]    - Sunday 03:00
2024-07-22 12:58:23 2024-07-22 12:58:23,061 buildarr:1 buildarr.cli.daemon [INFO] Scheduling update jobs
2024-07-22 12:58:23 2024-07-22 12:58:23,061 buildarr:1 buildarr.cli.daemon [INFO] Finished scheduling update jobs
2024-07-22 12:58:23 2024-07-22 12:58:23,061 buildarr:1 buildarr.cli.daemon [INFO] Enabling config file monitoring
2024-07-22 12:58:23 2024-07-22 12:58:23,071 buildarr:1 buildarr.cli.daemon [INFO] Finished enabling config file monitoring
2024-07-22 12:58:23 2024-07-22 12:58:23,072 buildarr:1 buildarr.cli.daemon [INFO] Applying initial configuration
2024-07-22 12:58:23 2024-07-22 12:58:23,089 buildarr:1 buildarr.cli.run [INFO] Loaded plugins: jellyseerr (0.3.2), prowlarr (0.5.3), radarr (0.2.6), sonarr (0.6.4)
2024-07-22 12:58:23 2024-07-22 12:58:23,089 buildarr:1 buildarr.cli.run [INFO] Loading instance configurations
2024-07-22 12:58:23 2024-07-22 12:58:23,093 buildarr:1 buildarr.cli.run [INFO] Finished loading instance configurations
2024-07-22 12:58:23 2024-07-22 12:58:23,093 buildarr:1 buildarr.cli.run [INFO] Running with plugins: prowlarr, radarr
2024-07-22 12:58:23 2024-07-22 12:58:23,093 buildarr:1 buildarr.cli.run [INFO] Resolving instance dependencies
2024-07-22 12:58:23 2024-07-22 12:58:23,093 buildarr:1 buildarr.cli.run [INFO] Finished resolving instance dependencies
2024-07-22 12:58:23 2024-07-22 12:58:23,093 buildarr:1 buildarr.cli.run [INFO] Fetching TRaSH metadata
2024-07-22 12:59:34 2024-07-22 12:59:34,346 buildarr:1 buildarr.cli.run [INFO] Finished fetching TRaSH metadata
2024-07-22 12:59:34 2024-07-22 12:59:34,346 buildarr:1 buildarr.cli.run [INFO] Rendering instance configuration dynamic attributes
2024-07-22 12:59:34 2024-07-22 12:59:34,346 buildarr:1 buildarr.cli.run [INFO] Finished rendering instance configuration dynamic attributes
2024-07-22 12:59:34 2024-07-22 12:59:34,346 buildarr:1 buildarr.cli.run [INFO] <prowlarr> (default) Fetching instance secrets
2024-07-22 12:59:34 2024-07-22 12:59:34,756 buildarr:1 buildarr.cli.daemon [ERROR] <prowlarr> (default) An error occurred while applying initial configuration: HTTPConnectionPool(host='prowlarr', port=9696): Max retries exceeded with url: /initialize.json (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7f9bdbe80090>: Failed to resolve 'prowlarr' ([Errno -2] Name does not resolve)"))
2024-07-22 12:59:34 Traceback (most recent call last):
2024-07-22 12:59:34   File "/usr/local/lib/python3.11/site-packages/urllib3/connection.py", line 196, in _new_conn
2024-07-22 12:59:34     sock = connection.create_connection(
2024-07-22 12:59:34            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-07-22 12:59:34   File "/usr/local/lib/python3.11/site-packages/urllib3/util/connection.py", line 60, in create_connection
2024-07-22 12:59:34     for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
2024-07-22 12:59:34                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-07-22 12:59:34   File "/usr/local/lib/python3.11/socket.py", line 962, in getaddrinfo
2024-07-22 12:59:34     for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
2024-07-22 12:59:34                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-07-22 12:59:34 socket.gaierror: [Errno -2] Name does not resolve
2024-07-22 12:59:34 
2024-07-22 12:59:34 The above exception was the direct cause of the following exception:
2024-07-22 12:59:34 
2024-07-22 12:59:34 Traceback (most recent call last):
2024-07-22 12:59:34   File "/usr/local/lib/python3.11/site-packages/urllib3/connectionpool.py", line 789, in urlopen
2024-07-22 12:59:34     response = self._make_request(
2024-07-22 12:59:34                ^^^^^^^^^^^^^^^^^^^
2024-07-22 12:59:34   File "/usr/local/lib/python3.11/site-packages/urllib3/connectionpool.py", line 495, in _make_request
2024-07-22 12:59:34     conn.request(
2024-07-22 12:59:34   File "/usr/local/lib/python3.11/site-packages/urllib3/connection.py", line 398, in request
2024-07-22 12:59:34     self.endheaders()
2024-07-22 12:59:34   File "/usr/local/lib/python3.11/http/client.py", line 1298, in endheaders
2024-07-22 12:59:34     self._send_output(message_body, encode_chunked=encode_chunked)
2024-07-22 12:59:34   File "/usr/local/lib/python3.11/http/client.py", line 1058, in _send_output
2024-07-22 12:59:34     self.send(msg)
2024-07-22 12:59:34   File "/usr/local/lib/python3.11/http/client.py", line 996, in send
2024-07-22 12:59:34     self.connect()
2024-07-22 12:59:34   File "/usr/local/lib/python3.11/site-packages/urllib3/connection.py", line 236, in connect
2024-07-22 12:59:34     self.sock = self._new_conn()
2024-07-22 12:59:34                 ^^^^^^^^^^^^^^^^
2024-07-22 12:59:34   File "/usr/local/lib/python3.11/site-packages/urllib3/connection.py", line 203, in _new_conn
2024-07-22 12:59:34     raise NameResolutionError(self.host, self, e) from e
2024-07-22 12:59:34 urllib3.exceptions.NameResolutionError: <urllib3.connection.HTTPConnection object at 0x7f9bdbe80090>: Failed to resolve 'prowlarr' ([Errno -2] Name does not resolve)
2024-07-22 12:59:34 
2024-07-22 12:59:34 The above exception was the direct cause of the following exception:
2024-07-22 12:59:34 
2024-07-22 12:59:34 Traceback (most recent call last):
2024-07-22 12:59:34   File "/usr/local/lib/python3.11/site-packages/requests/adapters.py", line 667, in send
2024-07-22 12:59:34     resp = conn.urlopen(
2024-07-22 12:59:34            ^^^^^^^^^^^^^
2024-07-22 12:59:34   File "/usr/local/lib/python3.11/site-packages/urllib3/connectionpool.py", line 843, in urlopen
2024-07-22 12:59:34     retries = retries.increment(
2024-07-22 12:59:34               ^^^^^^^^^^^^^^^^^^
2024-07-22 12:59:34   File "/usr/local/lib/python3.11/site-packages/urllib3/util/retry.py", line 519, in increment
2024-07-22 12:59:34     raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
2024-07-22 12:59:34     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-07-22 12:59:34 urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='prowlarr', port=9696): Max retries exceeded with url: /initialize.json (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7f9bdbe80090>: Failed to resolve 'prowlarr' ([Errno -2] Name does not resolve)"))
2024-07-22 12:59:34 
2024-07-22 12:59:34 During handling of the above exception, another exception occurred:
2024-07-22 12:59:34 
2024-07-22 12:59:34 Traceback (most recent call last):
2024-07-22 12:59:34   File "/usr/local/lib/python3.11/site-packages/buildarr/cli/daemon.py", line 215, in _initial_run
2024-07-22 12:59:34     run_apply()
2024-07-22 12:59:34   File "/usr/local/lib/python3.11/site-packages/buildarr/cli/run.py", line 208, in _run
2024-07-22 12:59:34     instance_secrets: SecretsPlugin = state.plugins[plugin_name].secrets.get(
2024-07-22 12:59:34                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-07-22 12:59:34   File "/usr/local/lib/python3.11/site-packages/buildarr_prowlarr/secrets.py", line 87, in get
2024-07-22 12:59:34     return cls.get_from_url(
2024-07-22 12:59:34            ^^^^^^^^^^^^^^^^^
2024-07-22 12:59:34   File "/usr/local/lib/python3.11/site-packages/buildarr_prowlarr/secrets.py", line 123, in get_from_url
2024-07-22 12:59:34     initialize_json = api_get(host_url, "/initialize.json")
2024-07-22 12:59:34                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-07-22 12:59:34   File "/usr/local/lib/python3.11/site-packages/buildarr_prowlarr/api.py", line 169, in api_get
2024-07-22 12:59:34     res = session.get(
2024-07-22 12:59:34           ^^^^^^^^^^^^
2024-07-22 12:59:34   File "/usr/local/lib/python3.11/site-packages/requests/sessions.py", line 602, in get
2024-07-22 12:59:34     return self.request("GET", url, **kwargs)
2024-07-22 12:59:34            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-07-22 12:59:34   File "/usr/local/lib/python3.11/site-packages/requests/sessions.py", line 589, in request
2024-07-22 12:59:34     resp = self.send(prep, **send_kwargs)
2024-07-22 12:59:34            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-07-22 12:59:34   File "/usr/local/lib/python3.11/site-packages/requests/sessions.py", line 703, in send
2024-07-22 12:59:34     r = adapter.send(request, **kwargs)
2024-07-22 12:59:34         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-07-22 12:59:34   File "/usr/local/lib/python3.11/site-packages/requests/adapters.py", line 700, in send
2024-07-22 12:59:34     raise ConnectionError(e, request=request)
2024-07-22 12:59:34 requests.exceptions.ConnectionError: HTTPConnectionPool(host='prowlarr', port=9696): Max retries exceeded with url: /initialize.json (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7f9bdbe80090>: Failed to resolve 'prowlarr' ([Errno -2] Name does not resolve)"))
2024-07-22 12:59:34 2024-07-22 12:59:34,764 buildarr:1 buildarr.cli.daemon [WARNING] Aborted applying initial configuration
2024-07-22 12:59:34 2024-07-22 12:59:34,764 buildarr:1 buildarr.cli.daemon [INFO] Setting up signal handlers
2024-07-22 12:59:34 2024-07-22 12:59:34,764 buildarr:1 buildarr.cli.daemon [INFO] Finished setting up signal handlers
2024-07-22 12:59:34 2024-07-22 12:59:34,764 buildarr:1 buildarr.cli.daemon [INFO] The next run will be at 2024-07-23 03:00
2024-07-22 12:59:34 2024-07-22 12:59:34,764 buildarr:1 buildarr.cli.daemon [INFO] Buildarr ready.
```

If I change the config to use localhost instead, the updates for Prowlarr work.

**Comment by kylelaverty** [comment]
I was able to address this by following the setup from: 
https://github.com/qdm12/gluetun-wiki/blob/main/setup/inter-containers-networking.md

Mainly, assigning the Gluetun container to a network that buildarr is also on.
